
api:
  prefix: api_social_network/v1

server:
  port: 8082

jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Socialnetwork?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: rapperyuki@gmail.com
    password: mcxn gern lfyw msle
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true